// <auto-generated />
namespace IKFAssignmentAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class schemaupdatedskillremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(schemaupdatedskillremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "202012211531430_schema-updated-skill-removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
